apiVersion: v1
kind: Service
metadata:
  name: {{ include "maghaze.fullname" . }}
  labels:
    {{- include "maghaze.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: management
      port: {{ .Values.service.management.port }}
      targetPort: management
      protocol: {{ .Values.service.management.protocol  }}
    - name: grpc
      port: {{ .Values.service.grpc.port }}
      targetPort: grpc
      protocol: {{ .Values.service.grpc.protocol  }}
  selector:
    {{- include "maghaze.selectorLabels" . | nindent 4 }}
